### ISSUE TITLE
How to export asset to obj file

### ISSUE THREAD

**Issue by leviome** [Spyispie120/NeRF-Rendering-Unity#1]
Hi, thanks for the nice sharing!
Following the steps, I built the fox.asset successfully. But I want to export to some other formats that can be opened by MeshLab(such as obj, mlb).
How can I make it?

**Comment by Spyispie120** [comment]
Hi there, thank you for checking out the blog.

To get obj file, I believe you can directly export from Instant-ngp tool itself. The tool provided a handy option called "Marching cube mesh output" that you can play around with after you finish training the dataset. I believe you can also generate color vertex with that option if you need color data.

However, the issue I found with that option is that, the mesh generated from the tool isn't that great most of the time. The tool mostly approximate using "marching cube" to generate mesh. I'm not too versed in the realm of NeRF, but getting a mesh from a radiance light field would be quite difficult since you will lose a lot of "light" & scene information that NeRF supposed to provide; And also defeated the purpose of NeRF. This project is mostly an attempt on different way to render the NeRF output that Instant-ngp provided (in this case 3D textures) to Unity. Maybe in the future NeRF technology can generate a better mesh from a few photos, but for now this is the best NeRF can provide. 

Hope this help. I would gladly answer any other question.

**Comment by leviome** [comment]
I appreciate your elaborate answer!

I have exported obj from instant-ngp tool, but the obj shows much worse than it shows on instant-ngp.  I found using Unity with steps in your blog can open the NGP result with high fidelity, so I wondered if there is a Unity way to export good-quality obj which is able to show on some portable platform like Meshlab. But it seems still a hard issue...

Thank you for your advice!

**Comment by Spyispie120** [comment]
Hi again @leviome ,
Sorry I didn't see notification on the response. In the case that you want the OBJ from NeRF, one software you that you can try is through https://lumalabs.ai/ .From my limited play time with their product, it does give you some what of a decent looking obj, but one again not fool proof.

In case you want a high quality model from images, I guess we can always go back to the traditional photogrammetry realm. Reality Capture is one of the software I mostly use for this. There are other free one like Meshroom. One down side to photogrammetry technique is it very time consuming.
